theme = ["FixIt", "shortcode-mmt-netease"]
title = "路奇的个人主页"
baseURL = "http://localhost:1313"
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
languageName = "简体中文"
hasCJKLanguage = false
[pagination]
  pagerSize = 10
copyright = ""
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
mainSections = []

[menu]
  [[menu.main]]
    identifier = "archives"
    parent = ""
    pre = ""
    post = ""
    name = "归档"
    url = "/archives/"
    title = ""
    weight = 1
    [menu.main.params]
      class = ""
      draft = false
      icon = "fa-solid fa-archive"
      type = ""
      divided = false
  [[menu.main]]
    identifier = "categories"
    parent = ""
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 2
    [menu.main.params]
      icon = "fa-solid fa-folder-tree"
  [[menu.main]]
    identifier = "tags"
    parent = ""
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 3
    [menu.main.params]
      icon = "fa-solid fa-tags"
  [[menu.main]]
    identifier = "about"
    parent = ""
    pre = ""
    post = ""
    name = "关于"
    url = "/about/"
    title = ""
    weight = 4
    [menu.main.params]
      icon = "fa-solid fa-tags"

[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = 'keywords'
  pattern = ''
  toLower = false
  type = 'basic'
  weight = 100
[[related.indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = 'date'
  pattern = ''
  toLower = false
  type = 'basic'
  weight = 10
[[related.indices]]
  applyFilter = false
  cardinalityThreshold = 0
  name = 'tags'
  pattern = ''
  toLower = false
  type = 'basic'
  weight = 80
[[related.indices]]
  applyFilter = false
  name = 'fragmentrefs'
  type = 'fragments'
  weight = 80

[module]
  [module.hugoVersion]
    extended = true
    min = "0.146.0"

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    guessSyntax = true
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = false
      table = true
      taskList = true
      typographer = true
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[sitemap]
  changefreq = "weekly"
  disable = false
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]
  post = "/:slugorcontentbasename/"

[privacy]
  [privacy.x]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]

[outputFormats]
  [outputFormats.archives]
    path = "archives"
    baseName = "index"
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
    permalinkable = true
    notAlternative = true
  [outputFormats.offline]
    path = "offline"
    baseName = "index"
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
    permalinkable = true
    notAlternative = true
  [outputFormats.readme]
    baseName = "readme"
    mediaType = "text/markdown"
    isPlainText = true
    isHTML = false
    notAlternative = true
  [outputFormats.baidu_urls]
    baseName = "baidu_urls"
    mediaType = "text/plain"
    isPlainText = true
    isHTML = false
    notAlternative = true
  [outputFormats.search]
    baseName = "search"
    mediaType = "application/json"
    rel = "search"
    isPlainText = true
    isHTML = false
    permalinkable = true

[outputs]
  home = ["html", "rss", "archives", "offline", "search"]
  page = ["html", "markdown"]
  section = ["html", "rss"]
  taxonomy = ["html"]
  term = ["html", "rss"]

[taxonomies]
  category = "categories"
  tag = "tags"
  collection = "collections"

[params]
  version = "0.3.X" # e.g. "0.2.X", "0.2.15", "v0.2.15" etc.
  description = ""
  keywords = []
  defaultTheme = "auto"
  fingerprint = ""
  dateFormat = "2006-01-02"
  images = []
  enablePWA = false
  externalIcon = false
  capitalizeTitles = true
  withSiteTitle = true
  titleDelimiter = "-"
  indexWithSubtitle = false
  summaryPlainify = false
  disableThemeInject = false
  [params.author]
    name = ""
    email = ""
    link = ""
    avatar = ""
  [params.gitInfo]
    repo = ""
    branch = "main"
    dir = "content"
    issueTpl = "title=[BUG]%20{title}&body=|Field|Value|%0A|-|-|%0A|Title|{title}|%0A|URL|{URL}|%0A|Filename|{sourceURL}|"
  [params.app]
    title = "FixIt"
    noFavicon = false
    svgFavicon = ""
    iconColor = "#5bbad5"
    tileColor = "#da532c"
    [params.app.themeColor]
      light = "#f8f8f8"
      dark = "#252627"
  [params.search]
    enable = false
    type = "fuse"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""
    [params.search.fuse]
      isCaseSensitive = false
      minMatchCharLength = 2
      findAllMatches = false
      location = 0
      threshold = 0.3
      distance = 100
      ignoreLocation = false
      useExtendedSearch = false
      ignoreFieldNorm = false
  [params.cse]
    engine = ""
    resultsPage = "/search/"
    [params.cse.google]
      cx = ""
    [params.cse.bing]
  [params.header]
    desktopMode = "sticky"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = ""
      pre = ""
      post = ""
      typeit = false
    [params.header.subtitle]
      name = ""
      typeit = false
  [params.breadcrumb]
    enable = false
    sticky = false
    showHome = false
    separator = "/"
    capitalize = true
  [params.navigation]
    inSection = false
    reverse = false
  [params.footer]
    enable = true
    copyright = true
    author = true
    since = ""
    gov = ""
    icp = ""
    license = ""
    [params.footer.powered]
      enable = true
      hugoLogo = true
      themeLogo = true
    [params.footer.siteTime]
      enable = false
      animate = true
      icon = "fa-solid fa-heartbeat"
      pre = ""
      value = "" # e.g. "2021-12-18T16:15:22+08:00"
    [params.footer.order]
      powered = 0
      copyright = 0
      statistics = 0
      visitor = 0
      beian = 0
  [params.archives]
    paginate = 20
    dateFormat = "01-02"
  [params.section]
    paginate = 20
    dateFormat = "01-02"
    [params.section.feed]
      limit = -1
      fullText = false
  [params.list]
    paginate = 20
    dateFormat = "01-02"
    [params.list.feed]
      limit = -1
      fullText = false
  [params.recentlyUpdated]
    archives = true
    section = true
    list = true
    days = 30
    maxCount = 10
  [params.tagcloud]
    enable = false
    min = 14 # Minimum font size in px
    max = 32 # Maximum font size in px
    peakCount = 10 # Maximum count of posts per tag
    orderby = "name" # Order of tags, optional values: ["name", "count"]
  [params.home]
    [params.home.profile]
      enable = true
      gravatarEmail = "lujianuse@163.com"
      avatarURL = "images/avatar.jpeg"
      avatarMenu = ""
      title = "你好，我是路奇 👋"
      subtitle = "跟随在优秀的人背后"
      typeit = true
      social = true
      disclaimer = ""
    [params.home.posts]
      enable = true
      paginate = 6
  [params.social]
    GitHub = "luqi678"
    Linkedin = ""
    Twitter = ""
    Instagram = ""
    Facebook = ""
    Telegram = "luqi678"
    Medium = ""
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Mastodon = ""
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    ORCID = ""
    Liberapay = ""
    Ko-Fi = ""
    BuyMeaCoffee = ""
    Linktree = ""
    QQ = "2645453519"
    QQGroup = "" # https://qun.qq.com/join.html
    Diaspora = ""
    CSDN = ""
    Discord = ""
    DiscordInvite = ""
    Lichess = ""
    Pleroma = ""
    Kaggle = ""
    MediaWiki= ""
    Plume = ""
    HackTheBox = ""
    RootMe = ""
    Feishu = ""
    TryHackMe = ""
    Douyin = ""
    TikTok = ""
    Credly = ""
    Bluesky = ""
    Phone = ""
    Email = "lujianuse@163.com"
    RSS = true
  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1
    loop = false
  [params.mermaid]
    themes = ["default", "dark"]
  [params.admonition]
  
  [params.taskList]
  [params.repoVersion]
    url = "https://github.com/hugo-fixit/FixIt/releases/tag/v"
    name = "FixIt"
  [params.pangu]
    enable = false
    selector = "article" # FixIt 0.2.17 | NEW
  [params.watermark]
    enable = false
    content = ""
    opacity = 0.1
    width = 150
    height = 20
    rowSpacing = 60
    colSpacing = 30
    rotate = 15
    fontSize = 0.85
    fontFamily = "inherit"
  [params.busuanzi]
    enable = false
    source = "https://vercount.one/js"
    siteViews = true
    pageViews = true
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""
    so = ""
    sogou = ""
  [params.seo]
    image = ""
    thumbnailUrl = ""
  [params.analytics]
    enable = false
    [params.analytics.google]
      id = ""
      anonymizeIP = true
    [params.analytics.fathom]
      id = ""
      server = ""
    [params.analytics.baidu]
      id = ""
    [params.analytics.umami]
      data_website_id = ""
      src = ""
      data_host_url = ""
      data_domains = ""
    [params.analytics.plausible]
      data_domain = ""
      src = ""
    [params.analytics.cloudflare]
      token = ""
    [params.analytics.splitbee]
      enable = false
      no_cookie = true
      do_not_track = true
      data_token = ""
  [params.cookieconsent]
    enable = true
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""
  [params.cdn]
    data = ""
  [params.compatibility]
    polyfill = false
    objectFit = false
  [params.githubCorner]
    enable = false
    permalink = "https://github.com/hugo-fixit/FixIt"
    title = "View source on GitHub"
    position = "right" # ["left", "right"]
  [params.gravatar]
    enable = false
    host = "www.gravatar.com" # ["cravatar.cn", "gravatar.loli.net", ...]
    style = "" # ["", "mp", "identicon", "monsterid", "wavatar", "retro", "blank", "robohash"]
  [params.backToTop]
    enable = true
    scrollpercent = false
  [params.readingProgress]
    enable = false
    start = "left"
    position = "top"
    reversed = false
    light = ""
    dark = ""
    height = "2px"
  
  [params.pace]
    enable = false
    color = "blue"
    theme = "minimal"
  
  [params.postChat]
    enable = false
    key = ""
    userMode = "iframe"
    addButton = true
    defaultInput = false
    left = ""
    bottom = ""
    width = ""
    height = ""
    fill = ""
    backgroundColor = ""
    upLoadWeb = true
    showInviteLink = true
    userTitle = ""
    userDesc = ""
    blackDom = []
    frameWidth = ""     # e.g. "375px"
    frameHeight = ""    # e.g. "600px"
    userIcon = ""
    defaultChatQuestions = []
    defaultSearchQuestions = []
    hotWords = true
  [params.postSummary]
    enable = false
    key = ""
    title = ""
    theme = ""
    postURL = ""
    blacklist = ""
    wordLimit = 1000
    typingAnimate = true
    beginningText = ""
    loadingText = true
  [params.feed]
    limit = 10
    fullText = true
    [params.feed.follow]
      feedId = ""
      userId = ""
  
  [params.image]
    cacheRemote = false
    optimise = false
  [params.customPartials]
    head = []
    menuDesktop = []
    menuMobile = []
    profile = []
    aside = []
    comment = []
    footer = []
    widgets = []
    assets = []
    postTocBefore = []
    postTocAfter = []
    postContentBefore = []
    postContentAfter = []
    postFooterBefore = []
    postFooterAfter = []
  [params.dev]
    enable = false
    c4u = false
  [params.page]
    authorAvatar = true
    hiddenFromHomePage = false
    hiddenFromSearch = false
    hiddenFromRelated = false
    hiddenFromFeed = false
    twemoji = false
    lightgallery = false
    ruby = true
    fraction = true
    fontawesome = true
    license = '<a rel="license external nofollow noopener noreferrer" href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
    linkToMarkdown = true
    linkToSource = true
    linkToEdit = true
    linkToReport = true
    linkToVscode = true
    pageStyle = "normal"
    autoBookmark = false
    wordCount = true
    readingTime = true
    endFlag = ""
    instantPage = false
    collectionList = false
    collectionNavigation = false
    [params.page.repost]
      enable = false
      url = ""
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
      position = "right"
      ordered = false
      startLevel = 2
      endLevel = 6
    [params.page.expirationReminder]
      enable = false
      reminder = 90
      warning = 180
      closeComment = false
    [params.page.heading]
      capitalize = false
      [params.page.heading.number]
        enable = false
        onlyMainSection = true
        [params.page.heading.number.format]
          h1 = "{title}"
          h2 = "{h2} {title}"
          h3 = "{h2}.{h3} {title}"
          h4 = "{h2}.{h3}.{h4} {title}"
          h5 = "{h2}.{h3}.{h4}.{h5} {title}"
          h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"
    [params.page.math]
      enable = true
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      copyTex = true
      mhchem = true
    [params.page.code]
      enable = true
      copy = true
      edit = true
      maxShownLines = 10
    [params.page.mapbox]
      accessToken = ""
      lightStyle = "mapbox://styles/mapbox/light-v11"
      darkStyle = "mapbox://styles/mapbox/dark-v11"
      navigation = true
      geolocate = true
      scale = true
      fullscreen = true
    [params.page.related]
      enable = false
      count = 5
      position = ["aside", "footer"]
    [params.page.reward]
      enable = false
      animation = false
      position = "after"
      mode = "static"
      [params.page.reward.ways]
    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = false
      Whatsapp = false
      Pinterest = false
      Tumblr = false
      HackerNews = false
      Reddit = false
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = true
      Myspace = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false
    [params.page.comment]
      enable = false
      [params.page.comment.artalk]
        enable = false
        server = "https://yourdomain"
        site = "默认站点"
        useBackendConf = false
        placeholder = ""
        noComment = ""
        sendBtn = ""
        editorTravel = true
        flatMode = "auto"
        lightgallery = false
        locale = "" # FixIt 0.2.15 | NEW
        emoticons = ""
        nestMax = 2
        nestSort = "DATE_ASC" # ["DATE_ASC", "DATE_DESC", "VOTE_UP_DESC"]
        vote = true
        voteDown = false
        uaBadge = true
        listSort = true
        imgUpload = true
        preview = true
        versionCheck = true
      [params.page.comment.disqus]
        enable = false
        shortname = ""
      [params.page.comment.gitalk]
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta = ['nick','mail','link']
        requiredFields = []
        pageSize = 10
        lang = ""
        visitor = true
        recordIP = true
        highlight = true
        enableQQ = false
        serverURLs = ""
        emoji = ""
        commentCount = true # FixIt 0.2.13 | NEW
      [params.page.comment.waline]
        enable = false
        serverURL = ""
        pageview = false # FixIt 0.2.15 | NEW
        emoji = ["//unpkg.com/@waline/emojis@1.1.0/weibo"]
        meta = ["nick", "mail", "link"]
        requiredMeta = []
        login = "enable"
        wordLimit = 0
        pageSize = 10
        imageUploader = false # FixIt 0.2.15 | NEW
        highlighter = false # FixIt 0.2.15 | NEW
        comment = false # FixIt 0.2.15 | NEW
        texRenderer = false # FixIt 0.2.16 | NEW
        search = false # FixIt 0.2.16 | NEW
        recaptchaV3Key = "" # FixIt 0.2.16 | NEW
        turnstileKey = "" # FixIt 0.3.8 | NEW
        reaction = false # FixIt 0.2.18 | NEW
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = ""
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false
      [params.page.comment.commento]
        enable = false
      [params.page.comment.utterances]
        enable = false
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
      [params.page.comment.twikoo]
        enable = false
        envId = ""
        region = ""
        path = ""
        visitor = true
        commentCount = true
        lightgallery = false
        katex = false
      [params.page.comment.giscus]
        enable = false
        repo = ""
        repoId = ""
        category = ""
        categoryId = ""
        mapping = ""
        origin = "https://giscus.app" # FixIt NEW | 0.3.7 Or set it to your self-hosted domain
        strict = "0" # FixIt NEW | 0.2.18
        term = ""
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom" # ["top", "bottom"]
        lang = ""
        lightTheme = "light"
        darkTheme = "dark"
        lazyLoad = true
    [params.page.library]
      [params.page.library.css]
      [params.page.library.js]
    [params.page.seo]
      images = []
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""